# Generated by Django 4.0.3 on 2022-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('peso', models.IntegerField()),
                ('altura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('detalle', models.CharField(max_length=80)),
                ('demostracion', models.CharField(max_length=40)),
                ('repeticiones', models.IntegerField()),
                ('duracion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('turno', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeticiones', models.IntegerField()),
                ('ejercicio1', models.CharField(max_length=40)),
                ('ejercicio2', models.CharField(max_length=40)),
                ('ejercicio3', models.CharField(max_length=40)),
                ('ejercicio4', models.CharField(max_length=40)),
                ('ejercicio5', models.CharField(max_length=40)),
                ('ejercicio6', models.CharField(max_length=40)),
            ],
        ),
    ]
