# Generated by Django 4.0.3 on 2022-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GimCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
